In [45]:
import pandas as pd

In [46]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\DIPANSHU SHUKLA\OneDrive\Desktop\SIH_162_ML\notebooks
['01_FIRMS_EDA.ipynb']

In [47]:
from pathlib import Path

Path(".").resolve()

WindowsPath('C:/Users/DIPANSHU SHUKLA/OneDrive/Desktop/SIH_162_ML/notebooks')

In [48]:
j1v_df = pd.read_csv("../data/raw/extracted/DL_FIRE_J1V-C2_793570/fire_archive_J1V-C2_793570.csv")

In [49]:
j1v_df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,21.95957,86.83456,351.88,0.75,0.77,2025-01-01,623,N20,VIIRS,n,2,293.33,15.17,D,0
1,21.95272,86.83650,343.37,0.75,0.77,2025-01-01,623,N20,VIIRS,n,2,292.51,9.03,D,0
2,21.95733,86.83066,355.85,0.75,0.77,2025-01-01,623,N20,VIIRS,n,2,295.66,25.92,D,0
3,27.28306,94.27637,326.12,0.41,0.45,2025-01-01,624,N20,VIIRS,n,2,295.71,2.36,D,0
4,22.94159,87.88538,333.14,0.62,0.71,2025-01-01,624,N20,VIIRS,n,2,294.63,5.77,D,0

In [50]:
j1v_df.shape

(664474, 15)

In [51]:
j1v_df.isnull().sum()

latitude      0
longitude     0
brightness    0
scan          0
track         0
acq_date      0
acq_time      0
satellite     0
instrument    0
confidence    0
version       0
bright_t31    0
frp           0
daynight      0
type          0
dtype: int64

In [52]:
j1v_df.duplicated().sum()

np.int64(0)

In [65]:
j1v_df.describe()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,version,bright_t31,frp,type
count,664474.000000,664474.000000,664474.000000,664474.000000,664474.000000,664474,664474,664474.0,664474.000000,664474.000000,664474.000000
mean,22.411421,81.165688,331.150755,0.452410,0.470061,2025-05-14 11:36:55.335437,1970-01-01 00:00:00.000001133,2.0,301.653400,6.303636,0.240956
min,8.078340,68.509750,207.930000,0.320000,0.360000,2025-01-01 00:00:00,1970-01-01 00:00:00.000000542,2.0,250.290000,0.000000,0.000000
25%,19.985383,77.240675,315.550000,0.390000,0.380000,2025-03-11 00:00:00,1970-01-01 00:00:00.000000733,2.0,293.970000,1.860000,0.000000
50%,22.561135,80.237255,335.090000,0.430000,0.440000,2025-04-02 00:00:00,1970-01-01 00:00:00.000000808,2.0,301.960000,3.480000,0.000000
75%,24.908910,83.995913,342.360000,0.500000,0.550000,2025-05-15 00:00:00,1970-01-01 00:00:00.000001941,2.0,308.500000,6.210000,0.000000
max,34.749180,97.040540,367.000000,0.800000,0.780000,2025-12-31 00:00:00,1970-01-01 00:00:00.000002203,2.0,379.690000,906.670000,3.000000
std,4.229777,5.507646,17.155721,0.081945,0.109490,NaN,NaN,0.0,9.880328,15.490309,0.655028

In [54]:
j1v_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 664474 entries, 0 to 664473
Data columns (total 15 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   latitude    664474 non-null  float64
 1   longitude   664474 non-null  float64
 2   brightness  664474 non-null  float64
 3   scan        664474 non-null  float64
 4   track       664474 non-null  float64
 5   acq_date    664474 non-null  str
 6   acq_time    664474 non-null  int64
 7   satellite   664474 non-null  str
 8   instrument  664474 non-null  str
 9   confidence  664474 non-null  str
 10  version     664474 non-null  int64
 11  bright_t31  664474 non-null  float64
 12  frp         664474 non-null  float64
 13  daynight    664474 non-null  str
 14  type        664474 non-null  int64
dtypes: float64(7), int64(3), str(5)
memory usage: 88.7 MB

In [55]:
j1v_df.columns.tolist()

['latitude',
 'longitude',
 'brightness',
 'scan',
 'track',
 'acq_date',
 'acq_time',
 'satellite',
 'instrument',
 'confidence',
 'version',
 'bright_t31',
 'frp',
 'daynight',
 'type']

In [56]:
j1v_df["acq_date"] = pd.to_datetime(j1v_df["acq_date"])

In [57]:
j1v_df["acq_time"] = pd.to_datetime(j1v_df["acq_time"])

In [58]:
j1v_df.nunique()

latitude      507997
longitude     517048
brightness      6281
scan              49
track             43
acq_date         365
acq_time         436
satellite          1
instrument         1
confidence         3
version            1
bright_t31      8074
frp             8172
daynight           2
type               4
dtype: int64

In [59]:
j1v_df["satellite"].value_counts()

satellite
N20    664474
Name: count, dtype: int64

In [60]:
j1v_df["instrument"].value_counts()

instrument
VIIRS    664474
Name: count, dtype: int64

In [61]:
j1v_df["confidence"].value_counts()

confidence
n    531979
l    115523
h     16972
Name: count, dtype: int64

In [62]:
j1v_df["version"].value_counts()

version
2    664474
Name: count, dtype: int64

In [63]:
j1v_df["daynight"].value_counts(dropna=False)

daynight
D    463703
N    200771
Name: count, dtype: int64

In [64]:
j1v_df["type"].value_counts(dropna=False)

type
0    584974
2     78257
3      1176
1        67
Name: count, dtype: int64

In [66]:
j1v_df["acq_time"].head(20)

0    1970-01-01 00:00:00.000000623
1    1970-01-01 00:00:00.000000623
2    1970-01-01 00:00:00.000000623
3    1970-01-01 00:00:00.000000624
4    1970-01-01 00:00:00.000000624
5    1970-01-01 00:00:00.000000624
6    1970-01-01 00:00:00.000000624
7    1970-01-01 00:00:00.000000624
8    1970-01-01 00:00:00.000000624
9    1970-01-01 00:00:00.000000624
10   1970-01-01 00:00:00.000000624
11   1970-01-01 00:00:00.000000624
12   1970-01-01 00:00:00.000000624
13   1970-01-01 00:00:00.000000624
14   1970-01-01 00:00:00.000000624
15   1970-01-01 00:00:00.000000624
16   1970-01-01 00:00:00.000000624
17   1970-01-01 00:00:00.000000624
18   1970-01-01 00:00:00.000000624
19   1970-01-01 00:00:00.000000625
Name: acq_time, dtype: datetime64[ns]

In [67]:
raw_j1v = pd.read_csv(
    "../data/raw/extracted/DL_FIRE_J1V-C2_793570/fire_archive_J1V-C2_793570.csv",
    dtype={"acq_time": str}
)

raw_j1v["acq_time"].head(20)

0     0623
1     0623
2     0623
3     0624
4     0624
5     0624
6     0624
7     0624
8     0624
9     0624
10    0624
11    0624
12    0624
13    0624
14    0624
15    0624
16    0624
17    0624
18    0624
19    0625
Name: acq_time, dtype: str

In [68]:
raw_j1v["hour"] = raw_j1v["acq_time"].str[:2].astype(int)
raw_j1v["minute"] = raw_j1v["acq_time"].str[2:4].astype(int)

raw_j1v[["acq_time", "hour", "minute"]].head(20)

   acq_time  hour  minute
0      0623     6      23
1      0623     6      23
2      0623     6      23
3      0624     6      24
4      0624     6      24
5      0624     6      24
6      0624     6      24
7      0624     6      24
8      0624     6      24
9      0624     6      24
10     0624     6      24
11     0624     6      24
12     0624     6      24
13     0624     6      24
14     0624     6      24
15     0624     6      24
16     0624     6      24
17     0624     6      24
18     0624     6      24
19     0625     6      25